CREATE DATABASE IF NOT EXISTS cybersecuritySRS;
USE cybersecuritySRS;

CREATE TABLE Users (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Username VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE Transfers (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    UserId INT NOT NULL,
    Title VARCHAR(255),
    Message TEXT,
    Link TEXT,
    ExpiryDate DATE,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserId) REFERENCES Users(Id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
)

CREATE TABLE Files (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    TransferId INT NOT NULL,
    FileSize BIGINT,
    FileName VARCHAR(255),
    FileType VARCHAR(255),
    StorageUrl TEXT,
    FOREIGN KEY (TransferId) REFERENCES Transfers(Id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
)

CREATE TABLE ErrorLogs (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    UserId INT NOT NULL,
    TransferId INT NOT NULL,
    ErrorType VARCHAR(255),
    ErrorMessage TEXT,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserId) REFERENCES Users(Id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (TransferId) REFERENCES Transfers(Id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
)

CREATE TABLE Recipients (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    TransferId INT NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Downloaded BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (TransferId) REFERENCES Transfers(Id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
)